version: "2.2"

services:
  spring-petclinic-native:
    image: spring-petclinic-native:3.0.0-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring-petclinic

  postgres:
    image: postgres:14
    mem_limit: 128m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    networks:
      - spring-petclinic

networks:
  spring-petclinic:
    driver: bridge
